version: '3'

services:

  dev:
    image: ai-devops-app
    container_name: ai-devops-dev
    ports:
      - "8081:5000"
    environment:
      - ENV=DEV

  test:
    image: ai-devops-app
    container_name: ai-devops-test
    ports:
      - "8082:5000"
    environment:
      - ENV=TEST

  prod:
    image: ai-devops-app
    container_name: ai-devops-prod
    ports:
      - "8083:5000"
    environment:
      - ENV=PROD